---
title: "baysys graphs"
author: "Nick Decker"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(ggplot2)
library(tidyverse)
library(janitor)
library(here)
```

```{r data load, include=FALSE}
sites <- read_csv(here("baysys_sites.csv")) %>% 
  clean_names()

underway <- read_csv(here("baysys_uw.csv")) %>% 
  clean_names()

compL <- read_csv(here("baysys_comp_L.csv")) %>% 
  clean_names() %>% 
  rename(pco2_out = p_co2_out_matm,
         pco2_meas = avg_pco2sw)

compM <- read_csv(here("baysys_comp_M.csv")) %>% 
  clean_names() %>% 
  rename(pco2_out = p_co2_out_matm,
         pco2_meas = avg_pco2sw)
```

```{r models}
model_L <- lm(pco2_out ~ pco2_meas, data = compL)
model_L_sum <- summary(model_L)


model_M <- lm(pco2_out ~ pco2_meas, data = compM)
model_M_sum <- summary(model_M)

```

```{r graphs}
compL %>% 
  ggplot() +
  geom_point(aes(x = pco2_meas, y = pco2_out, colour = s)) +
  geom_smooth(aes(x = pco2_meas, y = pco2_out), method = lm, se = FALSE) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", colour = "black") +
  theme_bw() +
  xlim(175, 575) +
  ylim(175, 575) +
  annotate(geom = "text",
           x = 175,
           y = 550,
           label = str_c("y = ",
                         round(model_L$coefficients[[2]], digits = 2),
                         "x",
                         " + ",
                         round(model_L$coefficients[[1]], digits = 2),
                         sep = ""),
           hjust = 0,
           vjust = 0) +
  annotate(geom = "text",
           x = 175,
           y = 550,
           label = str_c('R^2 ==',
                         round(model_L_sum$r.squared, digits = 2)),
           parse = TRUE,
           hjust = 0,
           vjust = 1.5) +
  labs(
    x = "Measured pCO2 (uatm)",
    y = "Calculated pCO2 (uatm)"
  )

compM %>% 
    ggplot() +
  geom_point(aes(x = pco2_meas, y = pco2_out, colour = s)) +
  geom_smooth(aes(x = pco2_meas, y = pco2_out), method = lm, se = FALSE) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", colour = "black") +
  theme_bw() +
  xlim(175, 575) +
  ylim(175, 575) +
  annotate(geom = "text",
           x = 175,
           y = 550,
           label = str_c("y = ",
                         round(model_M$coefficients[[2]], digits = 2),
                         "x",
                         " + ",
                         round(model_M$coefficients[[1]], digits = 2),
                         sep = ""),
           hjust = 0,
           vjust = 0) +
  annotate(geom = "text",
           x = 175,
           y = 550,
           label = str_c('R^2 ==',
                         round(model_M_sum$r.squared, digits = 2)),
           parse = TRUE,
           hjust = 0,
           vjust = 1.5) +
  labs(
    x = "Measured pCO2 (uatm)",
    y = "Calculated pCO2 (uatm)"
  )
```